-- Chilli 汉化词典 v3.2
-- 上传到 pastebin 后,把 raw 链接(https://pastebin.com/raw/xxxx)填进加载器的 DICT_URL 即可
local EXACT = {
    -- ===== Chilli 标签页 =====
    ["Main"]      = "主页",
    ["Misc"]      = "杂项",
    ["Predictor"] = "预测",
    ["Progress"]  = "进度",
    ["Quick"]     = "快捷",
    ["Auto Hop"]  = "自动换服",
    ["Player"]    = "玩家",
    ["Settings"]  = "设置",
    ["Farm"]      = "挂机",
    ["Server"]    = "服务器",

    -- ===== 分区 =====
    ["Performance"]            = "性能",
    ["Utility"]                = "实用工具",
    ["Egg Predictor"]          = "蛋预测",
    ["Discord Webhook"]        = "Discord 通知",
    ["Auto Progression"]       = "自动成长",
    ["Pin Pad"]                = "快捷键面板",
    ["Egg Finder"]             = "找蛋器",
    ["ESP"]                    = "透视",
    ["Character"]              = "角色",
    ["Movement"]               = "移动",
    ["Combat"]                 = "战斗",
    ["Interface"]              = "界面",
    ["Auto Steal"]             = "自动偷蛋",
    ["Auto Sell"]              = "自动出售",
    ["Dr Scramble Lab & Mech"] = "博士实验室 & 机甲Boss",
    ["Auto Hatch & Equip"]     = "自动孵化 & 装备",
    ["Auto Favorite"]          = "自动收藏",
    ["Community"]              = "社区",
    ["Defaults"]               = "默认设置",
    ["Profiles"]               = "配置档",
    ["Import / Export"]        = "导入 / 导出",
    ["Steal Filter Eggs"]      = "偷蛋筛选",
    ["Mech Boss"]              = "机甲Boss",
    ["Anti Guard"]             = "躲避守卫",
    ["Priority"]               = "优先级",

    -- ===== 杂项 / 性能 =====
    ["FPS Cap"]            = "FPS 上限",
    ["Farm HUD"]           = "挂机 HUD",
    ["Background Color"]   = "背景颜色",
    ["Egg Card Image"]     = "蛋卡片图片",
    ["Disable 3D Render"]  = "关闭 3D 渲染",
    ["FPS and Ping"]       = "FPS 与延迟",
    ["Optimizer"]          = "优化器",
    ["HUD Size"]           = "HUD 大小",
    ["Showcase Cards"]     = "展示卡片数",
    ["Hide Game UI"]       = "隐藏游戏界面",
    ["HUD Items"]          = "HUD 项目",
    ["FPS and Ping Size"]  = "FPS 与延迟大小",
    ["Anti AFK"]           = "防挂机踢出",
    ["Anti-AFK"]           = "防挂机踢出",
    ["Strip shadows, textures and effects for the highest FPS"] = "去除阴影、贴图和特效，换取最高 FPS",
    ["Drag any panel to place it where you like"]               = "把任意面板拖到你喜欢的位置",
    ["Picture used for Top Eggs and Steal History"]             = "顶级蛋和偷蛋记录使用的图片",
    ["White"]               = "白色",
    ["Black"]               = "黑色",

    -- ===== 预测 =====
    ["Sort By"]            = "排序方式",
    ["Preview Card"]       = "预览卡片",
    ["Webhook Min Rarity"] = "Webhook 最低稀有度",
    ["Webhook URL"]        = "Webhook 地址",
    ["Ping @everyone"]     = "通知所有人 (@everyone)",
    ["Notify Stolen Eggs"] = "蛋被偷时通知",
    ["Post every egg you bring home"] = "把你带回家的每个蛋都推送",
    ["Lab Predictor"]      = "实验室预测",
    ["Fuse Predictor"]     = "融合预测",
    ["Search eggs..."]     = "搜索蛋…",

    -- ===== 进度 =====
    ["Auto Buy Trail"]         = "自动买拖尾",
    ["Auto Claim Index"]       = "自动领图鉴奖励",
    ["Auto Upgrade Treadmill"] = "自动升级跑步机",
    ["Auto Claim"]             = "自动领取",
    ["Auto Upgrade Base"]      = "自动升级基地",
    ["Claim offline money & index rewards"]        = "领取离线收益和图鉴奖励",
    ["Claim index rewards as soon as they unlock"] = "图鉴奖励一解锁就领取",

    -- ===== 快捷 =====
    ["Pad Size"]            = "面板大小",
    ["Enable Keybinds"]     = "启用快捷键",
    ["Show Pin Pads"]       = "显示快捷面板",
    ["Visible Quick Bars"]  = "显示快捷栏",
    ["Quick Bar 1"]         = "快捷栏 1",
    ["Quick Bar 2"]         = "快捷栏 2",
    ["Quick Bar 3"]         = "快捷栏 3",
    ["Quick Bar 4"]         = "快捷栏 4",
    ["Quick Bar 5"]         = "快捷栏 5",
    ["Quick & Keys"]        = "快捷与按键",
    ["Quick Access"]        = "快捷访问",
    ["Quick Bar & Keybinds"] = "快捷栏与按键",
    ["Reset Quick Access"]  = "重置快捷访问",
    ["Restore default items, bars and positions"] = "恢复默认项目、快捷栏和位置",
    ["Reset Keybinds"]      = "重置快捷键",
    ["Restore the defaults set in code"] = "恢复代码里的默认键位",
    ["Turn off to disable every feature hotkey"] = "关闭后禁用所有功能热键",
    ["Show Quick Bars"]     = "显示快捷栏",
    ["Floating quick bars; drag a header to move one"] = "悬浮快捷栏；拖标题栏可移动",
    ["Quick Bar Size"]      = "快捷栏大小",
    ["Show notification cards; turning this off hides every notify"] = "显示通知卡片；关闭后隐藏所有通知",
    ["Open the UI automatically when the script starts"] = "脚本启动时自动打开界面",
    ["UI Toggle Key"]       = "界面开关键",
    ["Rebind"]              = "改键",

    -- ===== 自动换服 =====
    ["Hop Mode"]                     = "换服模式",
    ["Min Rarity"]                   = "最低稀有度",
    ["Rarity To Wait For"]           = "等待的稀有度",
    ["First Hop Delay"]              = "首次换服延迟",
    ["Target Specific Eggs"]         = "指定目标蛋",
    ["Sync With Auto Steal Filters"] = "同步自动偷蛋筛选",
    ["Min Value To Find"]            = "最低查找价值",
    ["Target Areas"]                 = "目标区域",
    ["Joins new servers to find eggs that match the filters below"] = "自动加入新服，寻找符合下方筛选的蛋",
    ["Finder Status"]                = "找蛋器状态",
    ["Steal Then Hop"]               = "偷完就换服",
    ["When to move on to the next server"] = "什么时候切换到下一个服务器",
    ["Find eggs of the chosen rarity and every rarity above it"] = "寻找所选稀有度及更高稀有度的蛋",
    ["Only look for these eggs (empty = all)"] = "只找这些蛋（留空=全部）",
    ["Wait after the script loads before the first hop"] = "脚本加载后先等待一段时间再首次换服",

    -- ===== 玩家 / 透视 =====
    ["ESP Eggs"]          = "蛋透视",
    ["ESP Show Info"]     = "蛋透视显示内容",
    ["ESP Player Size"]   = "玩家透视大小",
    ["ESP Player Info"]   = "玩家透视信息",
    ["ESP Guard Size"]    = "守卫透视大小",
    ["ESP Min Rarity"]    = "透视最低稀有度",
    ["ESP Guards"]        = "守卫透视",
    ["Min ESP Value"]     = "透视最低价值",
    ["ESP Lost Parts"]    = "失落零件透视",
    ["ESP Players"]       = "玩家透视",
    ["ESP Own Base Eggs"] = "自己基地的蛋透视",
    ["ESP Fixed Size"]    = "透视固定大小",
    ["ESP Egg Size"]      = "蛋透视大小",
    ["Icon"]              = "图标",
    ["Name"]              = "名字",
    ["Tool"]              = "工具",
    ["Mutation"]          = "变异",
    ["Size"]              = "体型",
    ["Sell Price"]        = "出售价",
    ["Distance"]          = "距离",
    ["Area"]              = "区域",
    ["State"]             = "状态",
    ["Username"]          = "用户名",
    ["Avatar"]            = "头像",
    ["Also show the eggs placed in your own base"] = "同时显示放在自己基地里的蛋",
    ["Show eggs of the chosen rarity and every rarity above it"] = "显示所选稀有度及更高稀有度的蛋",

    -- ===== 玩家 / 角色 =====
    ["Instant Prompts"] = "瞬间交互提示",
    ["Anti Ragdoll"]    = "防倒地",
    ["Anti Trap"]       = "防陷阱",
    ["Invisibility"]    = "隐身",
    ["Makes you invisible to other players"]       = "让其他玩家看不见你",
    ["Traps from other players cannot catch you"]  = "别人的陷阱困不住你",

    -- ===== 玩家 / 移动 =====
    ["Speed Boost"]   = "速度加成",
    ["Boost Speed"]   = "加成速度",
    ["Infinite Jump"] = "无限跳",

    -- ===== 玩家 / 战斗 =====
    ["Auto Hit Egg Holders"]     = "自动打拿蛋的人",
    ["Hit Max Speed"]            = "追击最大速度",
    ["Auto Hit Nearest Player"]  = "自动打最近的玩家",
    ["Hit Sweep"]                = "追击扫描范围",
    ["Hit Player"]               = "追击玩家",
    ["Hit Tween Speed"]          = "追击飞行速度",
    ["Hit Lead"]                 = "追击预判",
    ["Chase Settings"]           = "追击设置",
    ["Auto Hit Specific Player"] = "自动打指定玩家",
    ["Hit Aura"]                 = "攻击光环",
    ["Hit Status"]               = "追击状态",
    ["Idle"]                     = "待机",
    ["Stand further ahead of the target (+) or closer to them (-)"] = "站在目标前方更远处（+）或更贴近目标（-）",
    ["How far you move back and forth in front of the target"] = "在目标身前来回移动的幅度",
    ["Add/Remove Hits On Quick Bar 2"] = "在快捷栏2添加/移除攻击",
    ["Pin or unpin the hit toggles on Quick Bar 2"] = "固定/取消固定快捷栏2上的攻击开关",

    -- ===== 设置 / 界面 =====
    ["UI Size"] = "界面大小",
    ["Scales the main window; the corner grip does the same by hand"] = "缩放主窗口；也可以拖右下角手动缩放",

    -- ===== 挂机 / 自动偷蛋 =====
    ["Steal Missing Lab Eggs"]   = "偷缺失的实验蛋",
    ["Instant Steal Steps"]      = "瞬间偷取步数",
    ["Steal Priority"]           = "偷蛋优先级",
    ["Anti Guard Panel"]         = "躲避守卫面板",
    ["Stock Per Egg"]            = "每蛋囤货数",
    ["Experimental Lab Eggs"]    = "实验蛋选择",
    ["Unstable DNA Lab Eggs"]    = "不稳定DNA实验蛋",
    ["Skip Owned Lab Eggs"]      = "跳过已拥有的实验蛋",
    ["Carry Speed"]              = "搬蛋速度",
    ["Instant Steal"]            = "瞬间偷取",
    ["Steal Missing Index Eggs"] = "偷缺失图鉴的蛋",
    ["Min Steal Value"]          = "最低偷蛋价值",
    ["Tween Speed"]              = "飞行速度",
    ["Stock Lab Eggs For"]       = "囤实验蛋目标",
    ["Delivers the egg to the safe zone in a few seconds, needs enough Speed"] = "几秒内把蛋送回安全区，需要足够的速度",
    ["Higher is safer but takes longer"] = "越高越安全，但耗时更长",
    ["Steal eggs of the chosen rarity and every rarity above it"] = "偷取所选稀有度及更高稀有度的蛋",
    ["Skip eggs worth less than this. Drag or type 250k, 50m, 1.5b"] = "跳过低于此价值的蛋。可拖动或输入 250k、50m、1.5b",
    ["Only steal these eggs (empty = all)"] = "只偷这些蛋（留空=全部）",
    ["Also steal eggs missing from your index, highest area first"] = "同时偷图鉴里缺的蛋，从最高级区域开始",
    ["Only for the current recipe"] = "仅限当前配方",
    ["Collects eggs for these banners even before they open"] = "横幅还没开启时就会提前去收集蛋",
    ["Over 100% may glitch"] = "超过100%可能出bug",
    ["Highest Value"]        = "最高价值",
    ["Best Rarity"]          = "最高稀有度",
    ["Biggest Weight"]       = "最大重量",
    ["Best Mutation"]        = "最佳变异",
    ["Lowest Value"]         = "最低价值",
    ["Biggest Size"]         = "最大体型",
    ["Smallest Size"]        = "最小体型",
    ["Backpack Order"]       = "背包顺序",
    ["Steal Idle"]           = "偷蛋空闲时",
    ["After Steal"]          = "偷蛋后",
    ["Night Only"]           = "仅夜晚",

    -- ===== 挂机 / 自动出售 =====
    ["Egg Sell Value"]      = "卖蛋最低价值",
    ["Egg Sell Preview"]    = "卖蛋预览",
    ["Auto Sell Egg"]       = "自动卖蛋",
    ["Blacklist Sell Eggs"] = "卖蛋黑名单",
    ["Keep Mutated Eggs"]   = "保留变异蛋",
    ["Egg Max Rarity"]      = "卖蛋最高稀有度",
    ["Blacklist Sell Pets"] = "卖宠黑名单",
    ["Sell Egg Rule"]       = "卖蛋规则",
    ["Auto Sell Pet"]       = "自动卖宠",
    ["Pet Sell Value"]      = "卖宠最低价值",
    ["Pet Sell Preview"]    = "卖宠预览",
    ["Keep Mutated Pets"]   = "保留变异宠物",
    ["Sell Pet Rule"]       = "卖宠规则",
    ["Pet Max Rarity"]      = "卖宠最高稀有度",
    ["Which checks must pass to sell"] = "出售前需要满足哪些条件",
    ["Value Only"]          = "仅按价值",
    ["Rarity Only"]         = "仅按稀有度",
    ["Rarity Or Value"]     = "稀有度或价值",
    ["Rarity And Value"]    = "稀有度和价值",
    ["Sell pets at or below this rarity"] = "出售不高于此稀有度的宠物",
    ["Sell pets worth less than this (0 = off)"] = "出售低于此价值的宠物（0=关）",
    ["Never sell mutated pets"] = "永不出售变异宠物",
    ["These pets are never sold"] = "这些宠物永不出售",
    ["Sell bag eggs matching the rules below"] = "按下方规则出售背包里的蛋",
    ["Sell Eggs Now"]       = "立即卖蛋",
    ["Sell matching eggs once"] = "一次性卖出符合条件的蛋",
    ["Sell eggs at or below this rarity"] = "出售不高于此稀有度的蛋",
    ["Sell eggs worth less than this (0 = off)"] = "出售低于此价值的蛋（0=关）",
    ["Never sell mutated eggs"] = "永不出售变异蛋",
    ["Sell eggs traded from Dr Scramble that match the filters below"] = "出售从博士实验室换来的、符合下方筛选的蛋",
    ["Sell Lab Eggs Now"]   = "立即卖实验蛋",
    ["Sell matching Lab eggs once"] = "一次性卖出符合条件的实验蛋",
    ["Sell Lab eggs at or below this rarity (Off = none by rarity)"] = "出售不高于此稀有度的实验蛋（关=不按稀有度卖）",
    ["Sell Lab eggs worth less than this (0 = off)"] = "出售低于此价值的实验蛋（0=关）",
    ["Never sell mutated Lab eggs"] = "永不出售变异实验蛋",
    ["Lab eggs of these pets are never sold"] = "这些宠物的实验蛋永不出售",
    ["These eggs are never sold"] = "这些蛋永不出售",
    ["Sell Pets"]           = "卖宠物",
    ["Sell Pets Now"]       = "立即卖宠",

    -- ===== 挂机 / 博士实验室 & 机械Boss =====
    ["Swap Two Weapons"]           = "双武器轮换",
    ["Auto Lab Trade-In"]          = "自动实验室兑换",
    ["Keep Hopping For"]           = "持续换服时长",
    ["Mech Tween Speed"]           = "机甲飞行速度",
    ["Boss Server Hop"]            = "Boss换服",
    ["Auto Claim Mastery"]         = "自动领精通",
    ["Auto Buy Scramble Shop"]     = "自动购买扰乱商店物品",
    ["Scrambler Hold"]             = "扰乱器蓄力",
    ["Mutation Target Eggs"]       = "变异目标蛋",
    ["Mutation Priority"]          = "变异优先级",
    ["Min Mutation Value"]         = "最低变异价值",
    ["Mutation Min Rarity"]        = "变异最低稀有度",
    ["Scramble Shop Items"]        = "扰乱商店物品",
    ["Auto Mech Boss"]             = "自动打机甲Boss",
    ["Auto Reroll Lab Recipe"]     = "自动重摇实验室配方",
    ["Lab Banners"]                = "实验室横幅",
    ["Auto Use Scrambled"]         = "自动使用扰乱蛋",
    ["Auto Place Lab Reward Eggs"] = "自动放实验室奖励蛋",
    ["Auto Buy Scrambled"]         = "自动购买扰乱蛋",
    ["Lab Status"]                 = "实验室状态",
    ["Main Weapon Hold"]           = "主武器蓄力",
    ["Mech Status"]                = "机甲状态",
    ["Keep Samples"]               = "保留样本数",
    ["After each boss, hops to a less crowded server to fight again"] = "每个Boss打完后，换到人少的服务器再打",
    ["Keeps fighting every boss it finds and hopping for this long"] = "见到Boss就打并持续换服，保持这段时间",
    ["Claims Boss Mastery rewards as soon as they unlock"] = "Boss精通奖励一解锁就领取",
    ["Loading Lab data..."]        = "正在加载实验室数据…",
    ["Only trade and steal for these banners (empty = all)"] = "只为这些横幅兑换和偷蛋（留空=全部）",
    ["Places the reward eggs from Lab trades"] = "放置实验室兑换的奖励蛋",
    ["Buy the picked items with Samples"] = "用样本购买所选物品",
    ["Never spend below this many Samples"] = "样本低于这个数就不再花",
    ["Scrambled Status"]           = "扰乱状态",
    ["Turn it on to start applying Scrambled"] = "打开后开始使用扰乱蛋",
    ["Only eggs of this rarity and above are used"] = "只使用此稀有度及以上的蛋",
    ["Which egg gets the consumable first"] = "消耗品优先给哪个蛋",
    ["Only use the consumable on these eggs (empty = all)"] = "只对这些蛋使用消耗品（留空=全部）",
    ["Buy another Scrambled from the event shop when you run out"] = "用完后从活动商店再买一个扰乱蛋",

    -- ===== 挂机 / 自动放蛋 =====
    ["Place Egg Rule"]      = "放蛋规则",
    ["Auto Place Egg"]      = "自动放蛋",
    ["Pen Status"]          = "围栏状态",
    ["Place Rarities"]      = "放置稀有度",
    ["Place Egg Order"]     = "放蛋顺序",
    ["Min Place Value"]     = "最低放置价值",
    ["Place Specific Eggs"] = "指定放置的蛋",
    ["Only place eggs of the picked rarities (empty = all)"] = "只放所选稀有度的蛋（留空=全部）",
    ["Only place these eggs (empty = all)"] = "只放这些蛋（留空=全部）",
    ["Skip eggs worth less than this (0 = off)"] = "跳过低于此价值的蛋（0=关）",
    ["Pen status unknown"]  = "围栏状态未知",

    -- ===== 挂机 / 自动融合机 =====
    ["Max Rarity to Fuse"]       = "融合最高稀有度",
    ["Skip Mutated Pets"]        = "跳过变异宠物",
    ["Auto Fuse Machine"]        = "自动融合机",
    ["Eject Incomplete Slots"]   = "弹出未满槽位",
    ["Specific Species to Fuse"] = "指定融合物种",
    ["Pets To Use"]              = "宠物使用顺序",
    ["Fuse Priority Mode"]       = "融合优先模式",
    ["Fuse Preview"]             = "融合预览",
    ["Fuse status unknown"]      = "融合状态未知",
    ["Fuse 3 same pets into an egg, nonstop"] = "不停地把3只相同宠物融合成蛋",
    ["Highest Rarity First"]     = "最高稀有度优先",
    ["Most Copies First"]        = "重复最多优先",
    ["Lowest Value First"]       = "最低价值优先",
    ["Highest To Lowest"]        = "从高到低",
    ["Only fuse these species (empty = all)"] = "只融合这些物种（留空=全部）",
    ["Take out pets that can't make a set"] = "取出凑不成一套的宠物",
    ["Fuse Machine"]             = "融合机",
    ["Return"]                   = "返回",
    ["Pet Name"]                 = "宠物名",
    ["Empty"]                    = "空",
    ["Select Pets to Fuse!"]     = "选择要融合的宠物!",
    ["Select Pets to Sacrifice!"] = "选择要献祭的宠物!",
    ["Select Eggs to Sacrifice!"] = "选择要献祭的蛋!",

    -- ===== 挂机 / 自动出售实验蛋 =====
    ["Lab Egg Sell Value"]    = "实验蛋出售价值",
    ["Sell Lab Egg Rule"]     = "实验蛋出售规则",
    ["Lab Egg Max Rarity"]    = "实验蛋最高稀有度",
    ["Auto Sell Lab Egg"]     = "自动卖实验蛋",
    ["Lab Egg Sell Preview"]  = "实验蛋出售预览",
    ["Keep Lab Pets"]         = "保留实验宠物",
    ["Keep Mutated Lab Eggs"] = "保留变异实验蛋",
    ["Lab status unknown"]    = "实验室状态未知",

    -- ===== 挂机 / 自动孵化 & 装备 =====
    ["Hatch Specific Eggs"] = "指定孵化的蛋",
    ["Auto Hatch"]          = "自动孵化",
    ["Hatch Min Rarity"]    = "孵化最低稀有度",
    ["Min Hatch Value"]     = "最低孵化价值",
    ["Auto Equip Best"]     = "自动装备最好宠物",
    ["Equip Best"]          = "装备最佳",
    ["Hatch eggs of the chosen rarity and every rarity above it"] = "孵化所选稀有度及更高稀有度的蛋",
    ["Only hatch these eggs (empty = all)"] = "只孵这些蛋（留空=全部）",
    ["Equip Best when a better pet appears"] = "出现更好的宠物时自动换装",

    -- ===== 挂机 / 自动收藏 =====
    ["Favorite Mutations"]       = "收藏的变异",
    ["Favorite Preview"]         = "收藏预览",
    ["Auto Favorite Equipped"]   = "自动收藏已装备",
    ["Auto Favorite Pet"]        = "自动收藏宠物",
    ["Always Favorite Species"]  = "始终收藏的物种",
    ["Auto Unfavorite Equipped"] = "自动取消收藏已装备",
    ["Min Favorite Value"]       = "最低收藏价值",
    ["Favorite Rule"]            = "收藏规则",
    ["Favorite pets matching the rules below"] = "按下方规则收藏宠物",
    ["Favorite Pets Now"]        = "立即收藏宠物",
    ["Favorite matching pets once"] = "一次性收藏符合条件的宠物",
    ["Pass any check or all checks"] = "满足任一条件或全部条件",
    ["Match Any"]                = "任一满足",
    ["Match All"]                = "全部满足",
    ["Favorite Min Rarity"]      = "收藏最低稀有度",
    ["Favorite pets of the chosen rarity and every rarity above it (Off = skip)"] = "收藏所选稀有度及以上的宠物（关=跳过）",
    ["Mutation check (empty = skip)"] = "变异条件（留空=跳过）",
    ["Value check (0 = skip)"]   = "价值条件（0=跳过）",
    ["Always favorite these species"] = "始终收藏这些物种",
    ["Favorite Equipped Now"]    = "立即收藏已装备",
    ["Unfavorite Equipped Now"]  = "立即取消收藏已装备",
    ["Unfavorite"]               = "取消收藏",
    ["Favorite"]                 = "收藏",

    -- ===== 挂机 / 自动跑步机 =====
    ["Stay On Treadmill"] = "留在跑步机上",
    ["Auto Treadmill"]    = "自动跑步机",

    -- ===== 服务器 =====
    ["Server Hop Mode"]             = "换服模式",
    ["Auto Load Script"]            = "自动加载脚本",
    ["Auto Rejoin When Disconnect"] = "掉线自动重连",
    ["Rejoin"]                      = "重进本服",
    ["Server Hop"]                  = "切换服务器",
    ["Copy Job Id"]                 = "复制服务器ID",
    ["Copy Job ID"]                 = "复制服务器ID",
    ["Most Players"]                = "人最多",
    ["Least Players"]               = "人最少",
    ["Random"]                      = "随机",
    ["Hop"]                         = "换服",
    ["Job ID"]                      = "服务器ID",
    ["Paste a server Job ID..."]    = "粘贴服务器 Job ID…",
    ["Join Job ID"]                 = "加入指定服务器",
    ["Copy Current Job ID"]         = "复制当前服务器ID",
    ["Rejoin Server"]               = "重进服务器",

    -- ===== HUD 项目 =====
    ["Money"]         = "金钱",
    ["Income"]        = "收益",
    ["Speed"]         = "速度",
    ["Treadmill"]     = "跑步机",
    ["Eggs Stolen"]   = "已偷蛋数",
    ["Best Steal"]    = "最佳偷蛋",
    ["Night Timer"]   = "夜晚计时",
    ["Session Time"]  = "本次时长",
    ["Activity"]      = "活动",
    ["Mech Portal"]   = "机甲传送门",
    ["Boss Mastery"]  = "Boss精通",
    ["Samples"]       = "样本",
    ["Mech Fights"]   = "机甲战斗",
    ["Lab"]           = "实验室",
    ["Pets"]          = "宠物",
    ["Eggs"]          = "蛋",
    ["Top Pets"]      = "顶级宠物",
    ["Top Eggs"]      = "顶级蛋",
    ["Steal History"] = "偷蛋记录",

    -- ===== HUD / 偷蛋面板 =====
    ["Steal Panel"]  = "偷蛋面板",
    ["EGGS"]         = "蛋",
    ["READY"]        = "就绪",
    ["READY!"]       = "就绪!",
    ["GROWING"]      = "生长中",
    ["IN BAG"]       = "背包中",
    ["TOTAL / S"]    = "总计/秒",
    ["TASK PRIORITY"] = "任务优先级",
    ["Task Priority"] = "任务优先级",
    ["Top goes first. A carried egg is always delivered first."] = "排上方的先执行；搬着的蛋永远最先送回",
    ["RESET"]        = "重置",
    ["Steal"]        = "偷",
    ["Money/s:"]     = "金钱/秒:",
    ["MAX EQUIP"]    = "装备满员",
    ["19/19 Active"] = "19/19 出战",

    -- ===== 下拉选项 / 通用值 =====
    ["Value"]                = "价值",
    ["Any"]                  = "任意",
    ["Off"]                  = "关",
    ["On"]                   = "开",
    ["Until An Egg Matches"] = "直到刷到匹配的蛋",
    ["Always"]               = "总是",
    ["Lowest To Highest"]    = "从低到高",
    ["Lowest Rarity First"]  = "低稀有度优先",
    ["Pet Image"]            = "宠物图片",
    ["Egg Image"]            = "蛋图片",
    ["Forest"]               = "森林",
    ["Desert"]               = "沙漠",
    ["Snow"]                 = "雪地",
    ["Lake"]                 = "湖泊",
    ["Jungle"]               = "丛林",
    ["Volcano"]              = "火山",
    ["Prehistoric"]          = "史前",
    ["Cosmic"]               = "宇宙",
    ["Abyss Ocean"]          = "深渊海洋",
    ["Cherry Blossom"]       = "樱花",
    ["Light Dark"]           = "光暗",
    ["Titan Temple"]         = "泰坦神殿",

    -- ===== 变异类型 =====
    ["Any Mutation"]         = "任意变异",
    ["Fractured"]            = "碎裂",
    ["Golden"]               = "黄金",
    ["Parasite"]             = "寄生",
    ["Rainbow"]              = "彩虹",
    ["Scrambled Mutation"]   = "扰乱变异",
    ["Silver"]               = "白银",
    ["Scrambled"]            = "扰乱",

    -- ===== 宠物 / 蛋名 =====
    ["Bear"]                     = "熊",
    ["Cerberus"]                 = "地狱犬",
    ["Centaur"]                  = "半人马",
    ["Gorilla King"]             = "猩猩王",
    ["Gargoyle"]                 = "石像鬼",
    ["Ice Dragon"]               = "冰龙",
    ["Lava Dragon"]              = "熔岩龙",
    ["Kraken"]                   = "海妖",
    ["King Snake"]               = "王蛇",
    ["Chompa"]                   = "咬咬",
    ["Mosasaurus"]               = "沧龙",
    ["Mutant Shark"]             = "变异鲨鱼",
    ["Phoenix"]                  = "凤凰",
    ["Pink Dragon Experiment #010"] = "粉龙实验体#010",
    ["RazorFang"]                = "裂牙兽",
    ["Skeleton Horse"]           = "骷髅马",
    ["Stag"]                     = "雄鹿",
    ["Tralaledon"]               = "特拉拉顿",
    ["Unicorn"]                  = "独角兽",
    ["Yeti"]                     = "雪人",
    ["TRex"]                     = "霸王龙",
    ["Dreadstinger"]             = "恐惧刺尾",
    ["Eyeball Crab"]             = "眼球蟹",
    ["Frogfly"]                  = "蛙蝇",
    ["Nuceodile"]                = "核鳄",
    ["Nuclear Mantis"]           = "核螳螂",
    ["Octophant"]                = "章象",
    ["Radcoon"]                  = "辐射浣熊",
    ["Rhinobear"]                = "犀熊",
    ["Sharkodile"]               = "鲨鳄",
    ["Spiderpig"]                = "蜘蛛猪",
    ["Stacked Turtle"]           = "叠叠龟",
    ["Three Headed Chicken"]     = "三头鸡",
    ["Toucax"]                   = "巨嘴兽",
    ["Toxic Rat"]                = "毒鼠",
    ["Wheel Hamster"]            = "滚轮仓鼠",
    ["Balrog"]                   = "炎魔",
    ["El Maja"]                  = "玛雅树",
    ["Equinox"]                  = "昼夜兽",
    ["Gigantus"]                 = "巨人",
    ["Hazardhog"]                = "辐射刺猬",
    ["Krakenoid"]                = "海妖仔",
    ["Luminous Electric Eel"]    = "发光电鳗",
    ["Luminous Terra Snapper"]   = "发光大地龟",
    ["Mecha Crocodon"]           = "机甲鳄",
    ["Oni Tiger"]                = "鬼虎",
    ["Pegasus"]                  = "天马",
    ["Shattered Drake"]          = "破碎幼龙",
    ["Skeletal Dunkleosteus"]    = "骸骨邓氏鱼",
    ["Skeletal Gigantus"]        = "骸骨巨人",
    ["Strawberry Elephant"]      = "草莓象",
    ["Terra Snapper"]            = "大地龟",
    ["Void Dragon"]              = "虚空龙",
    ["Void Serpent"]             = "虚空蛇",
    ["World Eater"]              = "噬世者",
    ["Lunar Dragon"]             = "月龙",
    ["Jellyfish"]                = "水母",
    ["Crocodon"]                 = "鳄龙",
    ["Dunkleosteus"]             = "邓氏鱼",
    ["Salamander Egg"]           = "蝾螈蛋",
    ["Red Panda Egg"]            = "小熊猫蛋",
    ["Snowy Owl Egg"]            = "雪鸮蛋",
    ["Crane Egg"]                = "鹤蛋",
    ["Mantaris Egg"]             = "螳螂兽蛋",
    ["Pterodactyl Egg"]          = "翼龙蛋",
    ["Ankylosaurus Egg"]         = "甲龙蛋",
    ["Parrotfish Egg"]           = "鹦鹉鱼蛋",
    ["Centapede Egg"]            = "蜈蚣蛋",
    ["Dodo Egg"]                 = "渡渡鸟蛋",
    ["Swordfish Egg"]            = "剑鱼蛋",
    ["Koi Egg"]                  = "锦鲤蛋",
    ["La Vacca Saturno Saturnita Egg"] = "土星牛蛋",
    ["Shark Egg"]                = "鲨鱼蛋",
    ["Bronto Egg"]               = "雷龙蛋",
    ["Triceratops Egg"]          = "三角龙蛋",
    ["Orca Egg"]                 = "虎鲸蛋",
    ["Toro Egg"]                 = "公牛蛋",
    ["Winged Lamb Egg"]          = "飞羊蛋",
    ["Bladehide Egg"]            = "隐刃蛋",
    ["Imp Egg"]                  = "小恶魔蛋",
    ["Crustacia Egg"]            = "甲壳蛋",
    ["Sacred Moth Egg"]          = "圣蛾蛋",
    ["Demon Hound Egg"]          = "魔犬蛋",
    ["Holy Peacock Egg"]         = "圣孔雀蛋",
    ["Light Dove Egg"]           = "光鸽蛋",
    ["Flame Sprite Egg"]         = "火焰精灵蛋",
    ["Pure Jellyfish Egg"]       = "纯净水母蛋",
    ["Gargoyle Egg"]             = "石像鬼蛋",
    ["Rhinotaur Egg"]            = "犀牛兽蛋",
    ["Spideron Egg"]             = "蜘蛛兽蛋",
    ["Experiment Egg"]           = "实验蛋",
    ["Unstable Egg"]             = "不稳定蛋",
    ["Scrambled Experiment Egg"] = "扰乱实验蛋",
    ["Scrambled Unstable Egg"]   = "扰乱不稳定蛋",
    ["Random Scrambled Egg"]     = "随机扰乱蛋",
    ["Eye Bat"]                  = "眼蝠",
    ["Citadel Snail"]            = "城堡蜗牛",
    ["Uncoiled Armadillo"]       = "散卷犰狳",

    -- ===== 通用按钮 / 配置管理 =====
    ["Enable"]        = "开启",
    ["Disable"]       = "关闭",
    ["Yes"]           = "是",
    ["No"]            = "否",
    ["Confirm"]       = "确认",
    ["Cancel"]        = "取消",
    ["Buy"]           = "购买",
    ["Sell"]          = "出售",
    ["Equip"]         = "装备",
    ["Unequip"]       = "取消装备",
    ["Open"]          = "打开",
    ["Close"]         = "关闭",
    ["Hide"]          = "隐藏",
    ["Minimize"]      = "最小化",
    ["Destroy"]       = "卸载脚本",
    ["Destroy UI"]    = "卸载界面",
    ["Unload"]        = "卸载脚本",
    ["Reload"]        = "重载",
    ["Toggle UI"]     = "切换界面",
    ["Toggle"]        = "切换",
    ["Select"]        = "选择",
    ["Selected"]      = "已选择",
    ["All"]           = "全部",
    ["None"]          = "无",
    ["Refresh"]       = "刷新",
    ["Search"]        = "搜索",
    ["Search..."]     = "搜索…",
    ["No match"]      = "无匹配",
    ["Loading..."]    = "加载中…",
    ["Load"]          = "加载",
    ["Continue"]      = "继续",
    ["Free"]          = "免费",
    ["Profile"]       = "配置档",
    ["Create"]        = "创建",
    ["Delete"]        = "删除",
    ["Rename"]        = "重命名",
    ["Import"]        = "导入",
    ["Export"]        = "导出",
    ["Reset"]         = "重置",
    ["Copy"]          = "复制",
    ["Copied!"]       = "已复制!",
    ["Join"]          = "加入",
    ["Save"]          = "保存",
    ["Config"]        = "配置",
    ["Configs"]       = "配置",
    ["Configuration"] = "配置",
    ["Save Config"]   = "保存配置",
    ["Load Config"]   = "读取配置",
    ["Autoload"]      = "自动读取",
    ["Autoload Config"] = "自动读取配置",
    ["Notifications"] = "通知",
    ["Keybinds"]      = "快捷键",
    ["Menu Keybind"]  = "菜单快捷键",
    ["Open On Launch"] = "启动时自动打开",
    ["New Config Name"] = "新配置名称",
    ["New config name..."] = "输入新配置名称…",
    ["Create New Config"] = "创建新配置",
    ["Create New"]    = "新建",
    ["New config copies current settings"] = "新配置会复制当前设置",
    ["Delete Config"] = "删除配置",
    ["Tick the configs to remove, then press Delete"] = "勾选要删除的配置，然后按删除",
    ["Set Startup Config"] = "设置启动配置",
    ["Pick a config to auto load next time, then press Set"] = "选一个配置作为下次自动加载，然后按设置",
    ["Set Startup"]   = "设为启动",
    ["Pick a config, then press Load to apply it now"] = "选一个配置，按读取立即应用",
    ["Export Config"] = "导出配置",
    ["Pick a config, then press Export to copy its text"] = "选一个配置，按导出复制其文本",
    ["Import Config Text"] = "导入配置文本",
    ["Paste exported config JSON..."] = "粘贴导出的配置 JSON…",
    ["Import Config"] = "导入配置",
    ["Creates a config only; use Load Config or Set Startup after"] = "只创建配置；之后请用读取配置或设为启动",
    ["Reset to Defaults"] = "恢复默认设置",
    ["Reset every feature to its built-in default"] = "把所有功能恢复为内置默认值",
    ["Turn Off All Toggles"] = "一键关闭所有开关",
    ["Turn Off"]      = "全部关闭",
    ["Switch off every enabled toggle in the feature tabs"] = "关闭功能页里所有已开启的开关",
    ["Filter features..."] = "筛选功能…",
    ["Key System"]    = "密钥系统",
    ["Get Key"]       = "获取密钥",
    ["Check Key"]     = "验证密钥",
    ["Verify Key"]    = "验证密钥",
    ["Copy Link"]     = "复制链接",
    ["Join Discord"]  = "加入 Discord",
    ["Discord"]       = "Discord",
    ["Copy Discord Link"] = "复制 Discord 链接",
    ["Click"]         = "点击",
    ["Request features and vote on what gets added next."] = "请求功能，投票决定接下来加什么",
    ["Ask for help, report bugs and get answers from the team."] = "求助、报 bug、从团队获得解答",
    ["Member giveaways and events are announced in the server."] = "会员抽奖和活动会在服务器里公布",
    ["Patch notes and new game scripts are posted there first."] = "更新日志和新脚本会第一时间发在那里",
    ["Suggestions"]   = "功能建议",
    ["Support"]       = "支持",
    ["Giveaways"]     = "抽奖活动",
    ["New Scripts & Updates"]      = "新脚本与更新",
    ["New Scripts &amp; Updates"]  = "新脚本与更新",
    ["INVITE LINK"]   = "邀请链接",
    ["Members"]       = "成员",
    ["Official Discord Community"] = "官方 Discord 社区",
    ["Paste the copied link into your browser or the Discord app to join."] = "把复制的链接粘贴到浏览器或 Discord 应用，即可加入。",
    ["WHAT YOU GET"]  = "你获得的内容",
    ["Info"]          = "信息",
    ["Status"]        = "状态",
    ["Credits"]       = "作者",
    ["FPS"]           = "FPS",
    ["studs/s"]       = "格/秒",
    ["min"]           = "分",
    ["s"]             = "秒",

    -- ===== Discord 页 / 公告 =====
    ["SOMETHING BIG COMING SOON!"] = "重磅内容即将上线!",
    ["SKIP >>"]       = "跳过 >>",
    ["NEXT WEEK"]     = "下周",
    ["NEW BIOME..."]  = "新地形…",
    ["MONSTERS ARE"]  = "怪物们",
    ["COMING..."]     = "来了…",
    ["SAMMY IS"]      = "Sammy 的",
    ["DR. SCRAMBLE'S"] = "乱蛋博士",
    ["REVENGE..."]    = "复仇…",
    ["DR SCRAMBLE's"] = "乱蛋博士",
    ["EXPERIMENTS"]   = "实验体",
    ["NEXT TIME EACH BANNER OPENS"] = "下次各横幅开启时间",
    ["UPCOMING LAB BANNERS"] = "即将开放的实验室横幅",
    ["REWARD ODDS"]   = "奖励概率",
    ["BIOHAZARD PETS"] = "生化宠物",
    ["Chase pet"]     = "追捕宠物",
    ["ACTIVE"]        = "进行中",
    ["ETERNAL"]       = "永恒",
    ["SECRET"]        = "神秘",
    ["COSMIC"]        = "宇宙",
    ["MYTHIC"]        = "神话",
    ["DIVINE"]        = "神圣",
    ["LEGENDARY"]     = "传说",

    -- ===== 游戏内高频界面（顺带汉化）=====
    ["Time Left"]    = "剩余时间",
    ["Boss Shop"]    = "Boss 商店",
    ["Boss Tokens"]  = "Boss 代币",
    ["Current Mastery"] = "当前精通",
    ["1 Boss Kill = 1 Mastery"] = "杀 1 个 Boss = 1 点精通",
    ["Next Reward"]  = "下一档奖励",
    ["Mastery"]      = "精通",
    ["Get Reward Every"] = "每击杀",
    ["Kills"]        = "次可领奖",
    ["Claim"]        = "领取",
    ["Claimed"]      = "已领取",
    ["CLAIM!"]       = "领取!",
    ["CLAIMED!"]     = "已领取!",
    ["-- Reward --"] = "-- 奖励 --",
    ["Item Name"]    = "物品名",
    ["Rarity"]       = "稀有度",
    ["Weight"]       = "重量",
    ["2x Cash Booster"]     = "2倍现金加成",
    ["1.25x Speed"]         = "1.25倍速度",
    ["2x Treadmill Booster"] = "2倍跑步机加成",
    ["Mutation Consumable"] = "变异消耗品",
    ["WEATHER EVENT"] = "天气事件",
    ["THUNDERSTORM"]  = "雷暴",
    ["ELECTRIFIED"]   = "带电",
    ["CAPTURE THE EGG"] = "抢蛋模式",
    ["HOLD THE EGG TO EARN TIME"] = "拿着蛋即可累积时间",
    ["YOU!"]          = "是你!",
    ["The Rift"]      = "裂隙",
    ["TARGETED!"]     = "被锁定了!",
    ["The croc is coming for you. RUN!"] = "鳄鱼冲你来了，快跑!",
    ["HE'S OVERHEATING!"] = "它过热了!",
    ["Dr. Scramble"]  = "乱蛋博士",
    ["Dr. Scramble's Lab"] = "博士实验室",
    ["Dr. Scramble's Laboratory"] = "博士实验室",
    ["DR. SCRAMBLE'S MECH"] = "乱蛋博士的机甲",
    ["Leaving the base through the safe zone"] = "离开基地，途经安全区",
    ["Teleporting to the Mech portal"] = "正在传送到机甲传送门",
    ["Nobody showed up? Cowards! My mech waits for you in Titan Temple..."] = "没人来？胆小鬼！我的机甲在泰坦神殿等你…",
    ["ALL EGG RESET!"] = "全部蛋重置!",
    ["My MECH is complete! Find my portal in Titan Temple if you dare!"] = "我的机甲完成了！敢来就来泰坦神殿找我的传送门！",
    ["DR. SCRAMBLE'S MECH!"] = "乱蛋博士的机甲!",
    ["Jump in the portal at spawn and take him down!"] = "从出生点的传送门进去打它!",
    ["Admin"]         = "管理员",
    ["The Dragon Lair has opened!"] = "龙巢开启了!",
    ["Steal eggs and bring them back to your nest!"] = "偷蛋，带回你的巢穴!",
    ["Free Gift!"]    = "免费礼物!",
    ["10,000 SPEED!"] = "10000 速度!",
    ["~ LIMITED TIME! ~"] = "~ 限时! ~",
    ["1. Like the game!"] = "1. 给游戏点赞!",
    ["2. Favorite the game!"] = "2. 收藏游戏!",
    ["3. Join the community!"] = "3. 加入社区!",
    ["Unlocked!"]     = "已解锁!",
    ["Tap Anywhere to Skip"] = "点击任意位置跳过",
    ["The Great Bloom Has Begun!"] = "大绽放开始了!",
    ["Break trees, collect crystals and mutate your eggs!"] = "砸树、收水晶、变异你的蛋!",
    ["Break trees, collect crystals, mutate your eggs!"] = "砸树、收水晶、变异你的蛋!",
    ["COLLECT CRYSTALS"] = "收集水晶",
    ["DEPOSIT CRYSTALS"] = "存入水晶",
    ["MUTATE YOUR EGG"] = "变异你的蛋",
    ["2x Great Bloom Odds (0/3)"] = "2倍大绽放概率 (0/3)",
    ["The Hungry Monster Has Arrived!"] = "饥饿怪物降临!",
    ["Feed him parasites and claim his Monster Chest!"] = "喂它寄生虫，领走怪物宝箱!",
    ["FIND A PARASITE"] = "寻找寄生虫",
    ["FEED THE MONSTER"] = "喂怪物",
    ["CLAIM THE CHEST"] = "领取宝箱",
    ["MONSTER OBBY"]  = "怪物闯关",
    ["GET THE MOST WINS"] = "拿下最多胜利",
    ["MONSTER CHARGE"] = "怪物充能",
    ["MONSTER CHEST REWARDS"] = "怪物宝箱奖励",
    ["Reward Name"]   = "奖励名",
    ["(10 Minutes)"]  = "（10分钟）",
    ["Monster Chest"] = "怪物宝箱",
    ["The Hungry Monster"] = "饥饿怪物",
    ["Click on an egg to apply the mutation"] = "点击一个蛋使用变异",
    ["Choose an egg to mutate"] = "选择要变异的蛋",
    ["Possible Mutations"] = "可能出现的变异",
    ["Select an Egg"] = "选择一个蛋",
    ["Place Egg"]     = "放蛋",
    ["Remove Egg"]    = "取出蛋",
    ["Mutate"]        = "变异",
    ["Bloom"]         = "绽放",
    ["Spirit Bloom"]  = "灵花绽放",
    ["START"]         = "开始",
    ["CHARGE"]        = "充能",
    ["CHARGED"]       = "已充满",
    ["(Unlocks at 100%)"] = "（100% 解锁）",
    ["Sakura Crystals"] = "樱花水晶",
    ["Rescue the Dragon!"] = "拯救巨龙!",
    ["Steal x1 Egg from Desert Zone"] = "从沙漠区域偷 1 个蛋",
    ["In Progress"]   = "进行中",
    ["MONEY"]         = "金钱",
    ["SPEED"]         = "速度",
    ["PASSES"]        = "通行证",
    ["Get 2x Money"]  = "获得 2 倍金钱",
    ["x2 Growth"]     = "2倍生长",
    ["OWNED"]         = "已拥有",
    ["x2 Money"]      = "2倍金钱",
    ["2x Egg Growth"] = "2倍蛋生长",
    ["Watch Now!"]    = "立即观看!",
    ["-- MONEY --"]   = "-- 金钱 --",
    ["-- SPEED --"]   = "-- 速度 --",
    ["-- PASSES --"]  = "-- 通行证 --",
    ["-- FEATURED --"] = "-- 精选 --",
    ["-- SAMPLES --"] = "-- 样本 --",
    ["-- Current Egg --"] = "-- 当前蛋 --",
    ["-- Rotation Chances --"] = "-- 轮换概率 --",
    ["-- Riftbeasts Chances --"] = "-- 裂隙兽概率 --",
    ["-- Egg Chances --"] = "-- 蛋概率 --",
    ["-- Leaving In --"] = "-- 离开倒计时 --",
    ["Riftbeasts Banner"] = "裂隙兽横幅",
    ["Riftbeasts (Now)"] = "裂隙兽 (当前)",
    ["Riftborn"]      = "裂隙生",
    ["Shattered Rift"] = "破碎裂隙",
    ["PITY"]          = "保底",
    ["REROLL (2 free)"] = "重摇 (免费2次)",
    ["50,000 Samples"] = "50000 样本",
    ["(+5,000) Bonus"] = "(+5000) 奖励",
    ["Best Value!"]   = "最超值!",
    ["UPGRADE"]       = "升级",
    ["TREADMILL!"]    = "跑步机!",
    ["DOUBLE"]        = "双倍",
    ["Your SPEED"]    = "你的速度",
    ["50 Eggs"]       = "50 个蛋",
    ["10 Eggs"]       = "10 个蛋",
    ["3 Eggs"]        = "3 个蛋",
    ["1 Egg"]         = "1 个蛋",
    ["EXTINCTION EGG"] = "灭绝蛋",
    ["Limited Time!"] = "限时!",
    ["New!"]          = "新品!",
    ["Featured"]      = "精选",
    ["Sold Out"]      = "已售罄",
    ["SKELETAL"]      = "骸骨",
    ["CTULHU EGG"]    = "克苏鲁蛋",
    ["LUMINOUS"]      = "发光",
    ["LUMINOUS EGG"]  = "发光蛋",
    ["Going Away Soon!"] = "即将下架!",
    ["LAST CHANCE!"]  = "最后机会!",
    ["Check It Out"]  = "去看看",
    ["The Lab Trade-In"] = "实验室兑换",
    ["Egg Name"]      = "蛋名",
    ["Gift Player"]   = "赠送玩家",
    ["Gift"]          = "赠送",
    ["Cash gifts use the receiver's pack value, which may differ from yours."] = "现金礼物按接收方的背包价值计算，可能与你的不同。",
    ["Would you like to sell your pet?"] = "确定要出售这只宠物吗?",
    ["You don't have any pets in your inventory."] = "你背包里没有宠物。",
    ["Purchas successful! Thank you so much!"] = "购买成功! 非常感谢!",
    ["Select brainrot rarities to sell:"] = "选择要出售的稀有度:",
    ["(colored = keep, white = auto sell)"] = "（有色=保留，白色=自动出售）",
    ["Garden"]        = "花园",
    ["Eternal"]       = "永恒",
    ["Total Value:"]  = "总价值:",
    ["Sort By:"]      = "排序方式:",
    ["Clear"]         = "清空",
    ["Select All"]    = "全选",
    ["Background Music!"] = "背景音乐!",
    ["Music"]         = "音乐",
    ["SFX"]           = "音效",
    ["Sound Effects!"] = "音效!",
    ["View Other's Pets"] = "查看他人宠物",
    ["View Your Pets"] = "查看自己的宠物",
    ["Treadmill Videos"] = "跑步机视频",
    ["Menu Navigation"] = "菜单操作方式",
    ["Choose buttons or a cursor. Your choice is saved."] = "选择用按钮还是光标，你的选择会被保存。",
    ["Buttons"]       = "按钮",
    ["Buttons (Selected)"] = "按钮 (已选)",
    ["Cursor"]        = "光标",
    ["Add a comment"] = "添加评论",
    ["No comments yet!"] = "还没有评论!",
    ["Be the first to comment"] = "来抢第一条评论吧",
    ["TAP FOR NEXT VIDEO"] = "点击看下一条视频",
    ["ENJOY SOME FREE VIDEOS!"] = "看看免费视频!",
    ["Speed Shop"]    = "速度商店",
    ["+100 Speed"]    = "+100 速度",
    ["+100 Bonus Speed"] = "+100 额外速度",
    ["Get to 200 Speed"] = "达到 200 速度",
    ["STOLEN EXPERIMENT VAULT"] = "被盗实验保险库",
    ["Lost Parts"]    = "失落零件",
    ["Drone Parts"]   = "无人机零件",
    ["Dropped by Dr. Scramble's Drones"] = "乱蛋博士的无人机掉落",
    ["Vault incomplete"] = "保险库未完成",
    ["GOES AWAY IN"]  = "消失倒计时",
    ["Trail Shop"]    = "拖尾商店",
    ["Grey Trail"]    = "灰色拖尾",
    ["Green Trail"]   = "绿色拖尾",
    ["Blue Trail"]    = "蓝色拖尾",
    ["Purple Trail"]  = "紫色拖尾",
    ["Golden Trail"]  = "黄金拖尾",
    ["Red Trail"]     = "红色拖尾",
    ["Galaxy Trail"]  = "银河拖尾",
    ["Eternal Trail"] = "永恒拖尾",
    ["Moonbloom Trail"] = "月华拖尾",
    ["Sample Shop"]   = "样本商店",
    ["Reward ready"]  = "奖励已就绪",
    ["NEXT!"]         = "下一个!",
    ["Grow All"]      = "全部催熟",
    ["Growing Eggs"]  = "生长中的蛋",
    ["Index"]         = "图鉴",
    ["Shop"]          = "商店",
    ["Slow Mode"]     = "慢速模式",
    ["MAX"]           = "满级",
    ["Basic"]         = "基础",
    ["Rewards:"]      = "奖励:",
    ["Pet Index"]     = "宠物图鉴",
    ["World"]         = "世界",
    ["Limited"]       = "限定",
    ["Light Team"]    = "光明阵营",
    ["Dark Team"]     = "黑暗阵营",
    ["Your Team"]     = "你的阵营",
    ["Rings Collected"] = "已收集指环",
    ["Pick A Side!"]  = "选阵营!",
    ["Yes!"]          = "好!",
    ["Desc"]          = "描述",
    ["You're so lucky!"] = "你运气真好!",
    ["Goodbye!"]      = "再见!",
    ["Accept"]        = "接受",
    ["Decline"]       = "拒绝",
    ["OFF"]           = "关",
    ["ON"]            = "开",
    ["Instant Steal: OFF"] = "瞬间偷取: 关",
    ["Instant Steal: ON"] = "瞬间偷取: 开",
    ["Favorite: OFF"] = "收藏: 关",
    ["Favorite: ON"]  = "收藏: 开",
    ["Sort: Highest Value"] = "排序: 最高价值",
    ["Sort: Best Rarity"] = "排序: 最高稀有度",
    ["Sort: Biggest Weight"] = "排序: 最大重量",
    ["Sort: Best Mutation"] = "排序: 最佳变异",
    ["Sort: Lowest Value"] = "排序: 最低价值",
    ["Sort: Biggest Size"] = "排序: 最大体型",
    ["Sort: Smallest Size"] = "排序: 最小体型",
    ["Sort: Backpack Order"] = "排序: 背包顺序",
    ["Update Required"] = "需要更新",
    ["Restart Now"]   = "立即重启",

    -- ===== v3.2：游戏/Chilli 更新新增（来自 10-02 采集的 600+ 条真实文本）=====

    -- 新融合系统 / 实验室横幅
    ["DIVINE FUSION"]      = "神圣融合",
    ["ETERNAL FUSION"]     = "永恒融合",
    ["◇ AVAILABLE"]        = "◇ 可融合",
    ["◇ MISSING"]          = "◇ 缺失",
    ["◆ MISSING"]          = "◆ 缺失",
    ["DRAGON!"]            = "巨龙!",
    ["Creator server"]     = "创作者服务器",
    ["Collection"]         = "收集",
    ["Hide game UI"]       = "隐藏游戏界面",
    ["User ID"]            = "用户ID",
    ["-- Tabs --"]         = "-- 标签页 --",
    ["LAB"]                = "实验室",
    ["MONSTER EGG"]        = "怪物蛋",
    ["MECHA"]              = "机甲",
    ["Dog Poop"]           = "狗粑粑",
    ["CURRENT RECIPE"]     = "当前配方",
    ["Machine is empty"]   = "机器是空的",
    ["Next fuse"]          = "下次融合",
    ["Better pets"]        = "更好的宠物",
    ["give more"]          = "带来更多",
    ["Luck"]               = "运气",
    ["Experimental Pets Banner"]    = "实验宠物横幅",
    ["Unstable DNA Banner"]         = "不稳定DNA横幅",
    ["Biohazard Pets Banner"]       = "生化宠物横幅",
    ["-- Experimental Pets Chances --"] = "-- 实验宠物概率 --",
    ["-- Unstable DNA Chances --"]      = "-- 不稳定DNA概率 --",
    ["-- Biohazard Pets Chances --"]    = "-- 生化宠物概率 --",
    ["Experimental Pets"]  = "实验宠物",
    ["Biohazard Pets"]     = "生化宠物",
    ["Open now"]           = "现已开启",

    -- 新宠物/动物本体名（供前缀组合拼译）
    ["Dragon"]      = "龙",
    ["Skeleton"]    = "骸骨",
    ["Boss"]        = "Boss",
    ["Salamander"]  = "蝾螈",
    ["Crane"]       = "鹤",
    ["Dodo"]        = "渡渡鸟",
    ["Parrotfish"]  = "鹦鹉鱼",
    ["Pterodactyl"] = "翼龙",
    ["Ankylosaurus"] = "甲龙",
    ["Triceratops"] = "三角龙",
    ["Orca"]        = "虎鲸",
    ["Toro"]        = "公牛",
    ["Winged Lamb"] = "飞羊",
    ["Bladehide"]   = "隐刃",
    ["Imp"]         = "小恶魔",
    ["Crustacia"]   = "甲壳蟹",
    ["Sacred Moth"] = "圣蛾",
    ["Demon Hound"] = "魔犬",
    ["Holy Peacock"] = "圣孔雀",
    ["Light Dove"]  = "光鸽",
    ["Flame Sprite"] = "火焰精灵",
    ["Mantaris"]    = "螳螂兽",
    ["Snowy Owl"]   = "雪鸮",
    ["Red Panda"]   = "小熊猫",
    ["Rhinotaur"]   = "犀牛兽",
    ["Spideron"]    = "蜘蛛兽",
    ["Gorilla"]     = "大猩猩",
    ["Gecko"]       = "壁虎",
    ["Lava"]        = "熔岩",
    ["Bronto"]      = "雷龙",
    ["Scrambler"]   = "扰乱器",
    ["Experiment"]  = "实验体",
    ["Pink Dragon Experiment"] = "粉龙实验体",
    ["Nibbles"]     = "啃啃兽",
    -- Divine 阶
    ["Aetheron"]    = "以太神",
    ["ArchAngel"]   = "大天使",
    ["Archdemon Dragon"] = "大恶魔龙",
    ["Cthulhu"]     = "克苏鲁",
    ["Dreadscale"]  = "恐鳞龙",
    ["Kitsune"]     = "妖狐",
    ["Nightflame"]  = "夜焰",
    ["Sabertooth"]  = "剑齿虎",
    ["Colossus"]    = "巨像",
    ["World Burner"] = "焚世者",
    -- Secret 阶
    ["Abyss Overlord"] = "深渊霸主",
    ["Bombo Croco"] = "轰隆鳄",
    ["Electric Eel"] = "电鳗",
    ["Ember Dragon"] = "烬龙",
    ["Mawbreaker"]  = "碎口兽",
    ["Crawler"]     = "爬行者",
    ["Froggo"]      = "蛙蛙",
    ["Scorpio"]     = "天蝎",
    ["Ringlord"]    = "指环王",
    ["Scorched Dragon"] = "焦灼龙",
    ["Shardwing"]   = "碎翼龙",
    ["Giant Sloth"] = "大地懒",
    ["Glyptodon"]   = "雕齿兽",
    ["Terrorbird"]  = "骇鸟",
    ["Toxic Crocodile"] = "毒鳄",
    ["Toxic Hedgehog"] = "毒刺猬",
    ["Wendigo"]     = "温迪戈",
    ["Spike"]       = "尖刺兽",
    ["Abyss Shark"] = "深渊鲨",
    ["Depths"]      = "深渊",
    ["Riptide Octopus"] = "激流章鱼",
    ["Dreadclaw"]   = "恐爪兽",
    ["Drilla"]      = "钻头兽",
    ["Hellhound"]   = "地狱犬",
    ["King Mammoth"] = "猛犸王",
    ["Leviathan"]   = "利维坦",
    ["Mangolini Parrochini"] = "芒果鹦鹉",
    ["Ventinal"]    = "凡蒂娜",
    ["Whale Shark"] = "鲸鲨",
    ["Beluga Whale"] = "白鲸",
    ["Spirit Manta"] = "灵魔鬼鱼",
    -- Cosmic 阶
    ["Demon Imp"]   = "小恶魔",
    ["Ring Guard"]  = "指环守卫",
    ["Royal Sphinx"] = "皇家斯芬克斯",
    ["Shadow Dragon"] = "暗影龙",
    ["Shardling"]   = "碎晶仔",
    ["Spider"]      = "蜘蛛",
    ["Tiger"]       = "虎",
    ["Voidmaw"]     = "虚口兽",
    ["Void Angler"] = "虚空鮟鱇",
    ["Riftwing"]    = "裂隙翼",
    ["Rift Eye"]    = "裂隙之眼",
    ["Mammoth"]     = "猛犸",
    ["Belula Beluga"] = "贝鲁拉白鲸",
    -- Mythic / Legendary 阶
    ["Sabertooth Tiger"] = "剑齿虎",
    ["Sand Spider"] = "沙蛛",
    ["Scorpion"]    = "蝎子",
    ["Chillin Chilli"] = "悠闲辣椒",
    ["Cosmic Gorilla"] = "宇宙大猩猩",
    ["Cosmic Gecko"] = "宇宙壁虎",
    ["Axolotl"]     = "六角恐龙",
    ["Baby Aurora Dragon"] = "极光幼龙",
    ["Brr Brr Patapim"] = "帕塔彭",
    ["Flaming Bull"] = "烈焰公牛",
    ["Lava Iguana"] = "熔岩鬣蜥",
    ["Orangutini Ananassini"] = "猩猩菠萝",
    ["Polar Bear"]  = "北极熊",
    -- Epic / Rare / Uncommon / Common 阶
    ["Bananita Dolphinita"] = "香蕉海豚",
    ["Tob Tobi Tob Tob"] = "托比托布",
    ["Trulimero Trulicina"] = "特鲁利梅罗",
    ["Walrus"]      = "海象",
    ["Swan"]        = "天鹅",
    ["Crocodile"]   = "鳄鱼",
    ["Burrowing Owl"] = "穴鸮",
    ["Camel"]       = "骆驼",
    ["Chimpanzee"]  = "黑猩猩",
    ["Penguin"]     = "企鹅",
    ["Raccoon"]     = "浣熊",
    ["Toucan"]      = "托坎鸟",
    ["Tung Tung Sahur"] = "通通萨胡尔",
    ["Turtle"]      = "海龟",
    ["Snake"]       = "蛇",
    ["Shark"]       = "鲨鱼",
    ["Bird"]        = "鸟",
    ["Catfish"]     = "鲶鱼",
    ["Fennec"]      = "耳廓狐",
    ["Chicken"]     = "鸡",
    ["Duckling"]    = "小鸭",
    ["Frog"]        = "青蛙",
    ["Jerboa"]      = "跳鼠",

    -- 新区域 / 杂项
    ["Angels"]           = "天使",
    ["Demons"]           = "恶魔",
    ["demons"]           = "恶魔",
    ["Angels & Demons"]  = "天使与恶魔",
    ["Angelic"]          = "天使阶",
    ["Astral"]           = "星阶",
    ["Secret Trail"]     = "神秘拖尾",
    ["Divine Trail"]     = "神圣拖尾",
    ["Found in the biomes"] = "发现于各地形",
    ["Locked"]           = "未解锁",
    ["OPEN"]             = "已开启",
    ["IDLE"]             = "空闲",
    ["INCOMING!"]        = "来袭!",
    ["Phase"]            = "阶段",
    ["Common Area"]      = "公共区域",
    ["Ready"]            = "就绪",
    ["Ready!"]           = "就绪!",
    ["Ready."]           = "就绪.",
    ["NEXT"]             = "下一个",
    ["Default"]          = "默认",
    ["(OWNER)"]          = "(服主)",
    ["Boss Name Here"]   = "Boss名",
    ["Egg"]              = "蛋",
    ["EGG"]              = "蛋",

    -- Chilli 品牌与统计面板
    ["Chilli Hub"]       = "Chilli Hub",
    ["CHILLI HUB"]       = "CHILLI HUB",
    ["FARM STATS  |  STEAL AN EGG"] = "挂机数据  |  偷蛋",

    -- Chilli 新功能
    ["Auto Save Config"] = "自动保存配置",
    ["Auto Load Config"] = "自动加载配置",
    ["Turn on Auto Hop to start hunting"] = "打开自动换服后才会开始寻找",
    ["Include equipped pets"] = "包含已装备的宠物",
    ["No matching unequipped pets. Try including equipped pets."] = "没有匹配的未装备宠物，试试勾选包含已装备",
    ["Keep equipped pets favorited"] = "保持已装备的宠物处于收藏",
    ["Unfavorite equipped pets not in the rules"] = "取消收藏不符合规则的已装备宠物",
    ["Favorite all equipped pets once"] = "一次性收藏所有已装备宠物",
    ["Unfavorite all equipped pets once"] = "一次性取消收藏所有已装备宠物",
    ["After A Rare Spawns"] = "稀有蛋刷新后",
    ["For After A Rare Spawns: this rarity or higher"] = "稀有蛋刷新后：此稀有度及以上",
    ["Changing a filter here also changes it in Auto Steal, and back"] = "这里改筛选会同步到自动偷蛋，反之亦然",
    ["Automatically buy available trails when affordable"] = "钱够时自动购买可买的拖尾",
    ["Automatically upgrade base when money is available"] = "钱够时自动升级基地",
    ["Automatically upgrade treadmill when money is available"] = "钱够时自动升级跑步机",

    -- 挂机状态机（自动打机甲Boss的实时状态）
    ["Phase Mech, waiting for the boss"] = "机甲阶段，等待Boss出现",
    ["Phase Waiting, waiting for the boss"] = "等待阶段，等Boss出现",
    ["Ball phase, waiting for it to lock on"] = "球阶段，等它锁定目标",
    ["Smashing the core"] = "猛砸核心",
    ["Chasing Dr Scramble"] = "追击乱蛋博士",
    ["Fighting Mech"]    = "机甲战斗中",
    ["Fighting Ejecting"] = "弹射阶段",
    ["Dr Scramble defeated, going back home"] = "击败了乱蛋博士，回家",
    ["Respawned, going out through the safe zone"] = "已复活，经安全区出发",
    ["Respawned, resting in the safe zone"] = "已复活，在安全区休整",
    ["Back from the Mech arena, settling before the steal"] = "从机甲竞技场返回，偷蛋前先整顿",
    ["Waiting for mech"] = "等待机甲",
    ["Waiting for invisibility"] = "等待隐身",
    ["Turning invisible"] = "正在隐身",
    ["Cannot use items in the safe zone!"] = "安全区里不能使用道具!",
    ["Night, deciding egg or boss after the field resets"] = "夜晚，场地重置后决定偷蛋还是打Boss",
    ["Off  |  Mech portal is open now"] = "关  |  机甲传送门已开启",
    ["In the arena"]     = "已进竞技场",
    ["Running on the treadmill"] = "正在跑步机上跑步",
    ["No steals yet"]    = "还没有偷蛋记录",
    ["No eggs yet"]      = "还没有蛋",
    ["None yet"]         = "暂无",
    ["No item equipped."] = "没有装备道具.",
    ["Disconnected, rejoining now."] = "已掉线，正在重连.",
    ["Rewards claimed!"] = "奖励已领取!",
    ["You stole an EGG!"] = "你偷到了蛋!",
    ["Dr. Scramble:"]   = "乱蛋博士:",

    -- 大绽放/孵化器/救龙等活动新文案
    ["🌸 The Great Bloom has begun! 🌸"] = "🌸 大绽放开始了! 🌸",
    ["The Great Bloom"]  = "大绽放",
    ["Crystal Cherry Blossom Trees"] = "水晶樱花树",
    ["Charge the EMP Bar!"] = "给EMP条充能!",
    ["Charge Your Egg!"] = "给你的蛋充能!",
    ["Skip Growth!"]    = "跳过生长!",
    ["Incubator"]       = "孵化器",
    ["I hold mutation powers"] = "我掌握着变异之力",
    ["Friend Boost"]    = "好友加成",
    ["X2 Speed"]        = "2倍速度",
    ["Eggs Grow "]      = "蛋生长",
    [" faster!"]        = " 更快!",
    ["IMPORTANT PET UPDATE"] = "重要宠物更新",
    ["Hey!"]            = "你好!",
    ["RUN!!"]           = "快跑!!",
    ["CONFIDENTIAL DO NOT SHARE"] = "机密 请勿外传",
    ["Your pet was stronger than intended due to a bug. So its stats have been corrected. As compenstation, you've received this reward below:"] = "你的宠物因bug比预期更强，数据已被修正。作为补偿，你获得了以下奖励：",
    ["MISSIONS"]        = "任务",
    ["KEYS"]            = "钥匙",

    -- 游戏背包界面
    ["Backpack"]        = "背包",
    ["All Items"]       = "全部物品",
    ["Remove From Hotbar"] = "从快捷栏移除",
    ["Close Backpack"]  = "关闭背包",
    ["Drop"]            = "丢弃",
    ["Escape"]          = "脱离",
    ["Test"]            = "测试",
    ["Gear"]            = "装备",

    -- 创作者面板（房主工具）
    ["Creator Panel"]   = "创作者面板",
    ["Find a tool..."]  = "搜索工具…",
    ["TOOLS"]           = "工具",
    ["Camera"]          = "相机",
    ["Scene"]           = "场景",
    ["Servers"]         = "服务器",
    ["Manage"]          = "管理",
    ["Mutations"]       = "变异",
    ["My server"]       = "我的服务器",
    ["Join server"]     = "加入服务器",
    ["Server directory"] = "服务器目录",
    ["Send player"]     = "传送玩家",
    ["Manage whitelist"] = "管理白名单",
    ["Free camera"]     = "自由视角",
    ["Hide nameplates"] = "隐藏名牌",
    ["Movement speed"]  = "移动速度",
    ["Go to zone"]      = "前往区域",
    ["Invincibility"]   = "无敌",
    ["Guard disguise"]  = "伪装成守卫",
    ["Player disguise"] = "伪装成玩家",
    ["Spawn an egg"]    = "生成一个蛋",
    ["Give egg"]        = "给予蛋",
    ["Skip egg timer"]  = "跳过蛋计时",
    ["Give animal"]     = "给予宠物",
    ["Give event items"] = "给予活动道具",
    ["Spawn mutated pet"] = "生成变异宠物",
    ["Mutate a pen pet"] = "变异围栏宠物",
    ["Pause pursuit"]   = "暂停追捕",
    ["Stage a prank"]   = "策划恶作剧",
    ["Invite players"]  = "邀请玩家",
    ["Follow player"]   = "跟随玩家",
    ["Open creator server"] = "开启创作者服务器",
    ["Close creator server"] = "关闭创作者服务器",
    ["PUBLIC SERVER"]   = "公共服务器",
    ["Admin access"]    = "管理员权限",
    ["No matching tools."] = "没有匹配的工具.",
    ["CAMERA"]          = "相机",
    ["Find the perfect angle with a freely moving camera."] = "用自由移动的相机找到完美角度.",
    ["Search servers or user IDs..."] = "搜索服务器或用户ID…",
    ["< Tools"]         = "< 工具",
    ["HIDE OTHER UI DURING FREECAM"] = "自由视角时隐藏其他界面",
    ["HIDE FREECAM CONTROLS"] = "隐藏自由视角控件",
    ["Move freely to frame your shot. Keyboard: W A S D · Q / E Mouse: hold right button to look Touch: use the on-screen controls Controller: sticks and triggers"] = "自由取景。键盘: W A S D · Q / E；鼠标: 按住右键转视角；触屏: 用屏幕控件；手柄: 摇杆和扳机",
    ["< Back"]          = "< 返回",
    ["Choose an option"] = "选择一个选项",
    ["Search options..."] = "搜索选项…",
    ["Guest list"]      = "访客名单",
    ["Add guest"]       = "添加访客",
    ["Search guests or user IDs..."] = "搜索访客或用户ID…",
    ["No guests yet. Add someone to get started."] = "还没有访客，先添加一位吧",
    ["Username or user ID · press Enter or Add for each one"] = "用户名或用户ID · 逐个按回车或添加",
    ["Enter a username or user ID..."] = "输入用户名或用户ID…",
    ["Preview account"] = "预览账号",
    ["Add"]             = "添加",
    ["Are you sure?"]   = "确定吗?",
    ["Add this account to your server?"] = "把这个账号加进你的服务器?",
    ["Start your server to invite"] = "先开启你的服务器才能邀请",
    ["Username or user ID..."] = "用户名或用户ID…",
    ["Find"]            = "查找",
    ["Online in game"]  = "游戏中在线",
    ["Find someone to invite to this server."] = "找一位玩家邀请进这个服务器.",
    ["Invite player"]   = "邀请玩家",
    ["Find a player by username or user ID."] = "用用户名或用户ID查找玩家.",
    ["Disguise as player"] = "伪装成玩家",
    ["Ready to copy"]   = "已准备好复制",
    ["Disguise"]        = "伪装",
    ["SELECT AN OPTION"] = "选择一个选项",
    ["Choose..."]       = "请选择…",
    ["Option"]          = "选项",
    ["Animal name"]     = "宠物名",
    ["SELECTED"]        = "已选",
    ["Display name"]    = "显示名",
    ["Down"]            = "向下",
    ["Exit"]            = "退出",
    ["FREECAM  /  Drag to look"] = "自由视角 / 拖动查看",
    ["Back"]            = "返回",
    ["You're invited!"] = "你被邀请了!",
    ["You’re invited!"] = "你被邀请了!",
    ["Join their reserved server"] = "加入对方的专属服务器",
    ["Accept to leave this server and join them."] = "接受后将离开当前服务器并加入对方.",
    ["Accept & join"]   = "接受并加入",

    -- ===== v3.2 第二批：魔幻森林活动（10-04 更新）+ 创作者面板全文 =====
    ["ENCHANTED FOREST"] = "魔幻森林",
    ["Enchanted Forest"] = "魔幻森林",
    ["Butterfly Bloom"]  = "蝴蝶绽放",
    ["Wisp Companion"]   = "精灵伴侣",
    ["MOUNTS..."]        = "坐骑…",
    ["WHALE NAME"]       = "鲸鱼名",
    ["LION NAME"]        = "狮子名",
    ["ROYAL SKYWHALE"]   = "皇家天鲸",
    ["CELESTIAL SUNLION"] = "天界日狮",

    -- 新宠物（魔幻森林/裂隙生）
    ["Royal Skywhale"]   = "皇家天鲸",
    ["Celestial Sunlion"] = "天界日狮",
    ["Spirit World Guardian"] = "灵界守卫",
    ["Amethyst Runebear"] = "紫晶符熊",
    ["Jitterbug"]        = "颤虫",
    ["Starry Fox"]       = "星光狐",
    ["Astral Jackalope"] = "星界鹿兔",
    ["Spirit Panda"]     = "灵熊猫",
    ["Enchanted Bluejay"] = "魔蓝松鸦",
    ["Petal Beetle"]     = "花瓣甲虫",
    ["Prism Gecko"]      = "棱镜壁虎",
    ["Riftborn Banner"]  = "裂隙生横幅",
    ["-- Riftborn Chances --"] = "-- 裂隙生概率 --",
    ["Riftbeasts"]       = "裂隙兽",

    -- Chilli 新分区：蝴蝶绽放
    ["Auto Butterfly Bloom"] = "自动蝴蝶绽放",
    ["Catch Mode"]      = "捕捉模式",
    ["Stand"]           = "原地",
    ["Chase"]           = "追捕",
    ["Circle"]          = "绕圈",
    ["Patrol"]          = "巡逻",
    ["Catch Priority"]  = "捕捉优先级",
    ["Only for Chase mode"] = "仅追捕模式生效",
    ["Nearest"]         = "最近的",
    ["Catch Butterflies"] = "捕捉蝴蝶",
    ["Auto Trade Up"]   = "自动升级蝴蝶",
    ["Trade Up Tiers"]  = "升级档位",
    ["Emerald To Sapphire"] = "绿宝石→蓝宝石",
    ["Sapphire To Amethyst"] = "蓝宝石→紫晶",
    ["Amethyst To Radiant"] = "紫晶→辉光",
    ["Smart Trade For Essence"] = "智能换精华",
    ["Auto Craft Essence"] = "自动合成精华",
    ["Auto Use Enchanted Essence"] = "自动使用魔幻精华",
    ["Essence Min Rarity"] = "精华最低稀有度",
    ["Only eggs of this rarity and above get the essence"] = "只对此稀有度及以上的蛋使用精华",
    ["Essence Min Value"] = "精华最低价值",
    ["Essence Target Eggs"] = "精华目标蛋",
    ["Only use the essence on these eggs (empty = all)"] = "只对这些蛋使用精华（留空=全部）",
    ["Essence Priority"] = "精华优先级",
    ["Which egg gets the essence first"] = "精华优先给哪个蛋",
    ["Essence Skip Enchanted Eggs"] = "跳过已魔化的蛋",
    ["Skip eggs that already got Enchanted, other mutations still get the essence"] = "跳过已魔化的蛋，带其他变异的蛋仍会使用精华",

    -- Chilli 新分区：精灵伴侣
    ["Auto Wisp"]       = "自动精灵",
    ["Auto Banjo Cricket"] = "自动斑卓蟋蟀",
    ["Steal Wisp Quest Eggs"] = "偷精灵任务蛋",
    ["Loaded"]          = "已加载",
    ["Enchanted"]       = "魔化",
    ["Butterflies"]     = "蝴蝶",

    -- 游戏活动界面
    ["EMERALD BUTTERFLY"] = "绿宝石蝴蝶",
    ["SAPPHIRE BUTTERFLY"] = "蓝宝石蝴蝶",
    ["AMETHYST BUTTERFLY"] = "紫晶蝴蝶",
    ["RADIANT BUTTERFLY"] = "辉光蝴蝶",
    ["Emerald Butterfly"] = "绿宝石蝴蝶",
    ["Sapphire Butterfly"] = "蓝宝石蝴蝶",
    ["Amethyst Butterfly"] = "紫晶蝴蝶",
    ["Radiant Butterfly"] = "辉光蝴蝶",
    ["*Choose Recipe*"]  = "*选择配方*",
    ["Butterfly Trade Up"] = "蝴蝶升级",
    ["Enchanted Mutation Shrine"] = "魔化变异祭坛",
    ["Craft"]           = "合成",
    ["Enchanted Essence"] = "魔幻精华",
    ["Guarantees Mutation!"] = "必出变异!",
    ["Need More Butterflies"] = "蝴蝶不够",
    ["Craft Enchanted Essence with butterflies!"] = "用蝴蝶合成魔幻精华!",
    ["Uses 10 Emerald Butterflies to make 1 Sapphire Butterfly"] = "用 10 只绿宝石蝴蝶换 1 只蓝宝石蝴蝶",
    ["TRADE UP"]        = "蝴蝶升级",
    ["Return to the Beanstalk"] = "回到豆茎",
    ["Catch Fireflies"] = "捉萤火虫",
    ["Water the Beanstalk"] = "给豆茎浇水",
    ["Fly to the Top!"] = "飞向顶端!",
    ["Wisp Challenge"]  = "精灵挑战",
    ["Complete quests, gather Essence, and help your Wisp grow."] = "完成任务、收集精华，帮助精灵成长",
    ["Your quests"]     = "你的任务",
    ["Explore Enchanted Forest"] = "探索魔幻森林",
    ["Complete all 4 stages"] = "完成全部 4 个阶段",
    ["Grow your Wisp to open the hidden tree entrance."] = "培养精灵，开启隐藏的树洞入口",
    ["Baby Wisp"]       = "精灵宝宝",
    ["Grow Your Wisp"]  = "培养精灵",
    ["Completed"]       = "已完成",
    ["-- QUESTS --"]    = "-- 任务 --",
    ["Talk to the Baby Wisp"] = "去找精灵宝宝对话",
    ["Fuse an Enchanted Forest animal"] = "融合一只魔幻森林动物",
    ["Steal any Eternal"] = "偷任意永恒宠物",
    ["Complete all 3 quests"] = "完成全部 3 个任务",
    ["RETURN THE WISP"] = "送回精灵",
    ["Meet the Baby Wisp"] = "见一见精灵宝宝",
    ["RED LIGHT, GREEN LIGHT"] = "红绿灯游戏",
    ["BRING THE EGG BACK TO SPAWN"] = "把蛋带回出生点",
    ["GET READY"]       = "准备!",
    ["Steal the TRex Egg!"] = "偷霸王龙蛋!",
    ["Demonic"]         = "恶魔阶",

    -- 创作者面板完整文案
    ["Enabled"]         = "已启用",
    ["Hide other UI during freecam"] = "自由视角时隐藏其他界面",
    ["Hide freecam controls"] = "隐藏自由视角控件",
    ["Keep the action in focus. This panel stays accessible."] = "保持画面聚焦，此面板仍可访问",
    ["A cleaner shot without player labels."] = "没有玩家名牌的干净画面",
    ["Watch from another player's point of view. Nothing on screen shows it."] = "以其他玩家视角观看，画面上不会有任何显示",
    ["Spectate player"] = "观战玩家",
    ["Spectate"]        = "观战",
    ["Stop"]            = "停止",
    ["Set your movement speed for the scene."] = "设置场景中的移动速度",
    ["Walk speed"]      = "行走速度",
    ["Apply"]           = "应用",
    ["Jump straight to any zone."] = "直接跳到任意区域",
    ["Zone"]            = "区域",
    ["Stay protected from guards and player attacks."] = "免受守卫和玩家的攻击",
    ["Wear a guard's appearance for your scene."] = "在场景中穿上守卫外形",
    ["Guard look"]      = "守卫外形",
    ["Turn yourself or another player into an egg."] = "把你或另一名玩家变成蛋",
    ["Egg disguise"]    = "蛋形态伪装",
    ["Animal / egg"]    = "宠物 / 蛋",
    ["Look like another player by username or user ID."] = "通过用户名或用户ID伪装成其他玩家",
    ["Place an egg in this server for everyone to see and collect."] = "在本服放一个蛋，所有人可见可捡",
    ["Random size"]     = "随机大小",
    ["Spawn"]           = "生成",
    ["Grant eggs. They last for this session only and never save."] = "发放蛋，仅本次会话有效，不会保存",
    ["Give"]            = "给予",
    ["Choose one placed egg and make it ready to hatch."] = "选一个已放的蛋，让它直接可以孵化",
    ["Placed egg"]      = "已放的蛋",
    ["Choose an egg"]   = "选择一个蛋",
    ["Skip timer"]      = "跳过计时",
    ["Grant animals. They last for this session only and never save."] = "发放宠物，仅本次会话有效，不会保存",
    ["Grant an event's currency or its mutation consumable. It lasts for this session only and never saves."] = "发放活动货币或变异消耗品，仅本次会话有效，不会保存",
    ["What to give"]    = "发放内容",
    ["Grant a pet that already has a mutation. It lasts for this session only and never saves."] = "发放一只已变异的宠物，仅本次会话有效，不会保存",
    ["Change the mutation on a pet in your pen. The change lasts for this session only and never saves."] = "修改围栏中宠物的变异，仅本次会话有效，不会保存",
    ["Pen pet"]         = "围栏宠物",
    ["Choose a pet"]    = "选择一只宠物",
    ["No mutation"]     = "无变异",
    ["Run an event in this server. Starting one replaces the event already running."] = "在本服开启活动，会替换当前进行中的活动",
    ["Start server event"] = "开启服务器活动",
    ["Server event"]    = "服务器活动",
    ["Start event"]     = "开启活动",
    ["End the event running in this server."] = "结束本服当前进行的活动",
    ["Cancel server event"] = "取消服务器活动",
    ["Cancel event"]    = "取消活动",
    ["Send a message to this server under your own name."] = "以你的名义向本服发送消息",
    ["Announcement"]    = "公告",
    ["Message"]         = "消息",
    ["Type your announcement"] = "输入公告内容",
    ["Send"]            = "发送",
    ["Stop guards in a selected zone from chasing you."] = "让所选区域的守卫停止追你",
    ["Guards to pause"] = "暂停守卫",
    ["Fling, slip, or drop a carried egg in a creator server."] = "在创作者服务器里把玩家击飞/滑倒，或掉落其搬运的蛋",
    ["Prank"]           = "恶作剧",
    ["Run prank"]       = "执行恶作剧",
    ["Start your own recording server, then invite who you want."] = "开启你自己的录制服务器，再邀请想要的人",
    ["Step into your next recording session."] = "进入你的下一次录制",
    ["View creator servers and manage their guest lists."] = "查看创作者服务器并管理访客名单",
    ["Send a player in this session to an approved creator server."] = "把本局玩家送进已批准的创作者服务器",
    ["Preview and add guests by username or user ID, including offline accounts."] = "用用户名或用户ID预览并添加访客，支持离线账号",
    ["Manage guests"]   = "管理访客",
    ["Invite a player from another server, or send a Roblox invitation."] = "邀请其他服务器的玩家，或发送 Roblox 邀请",
    ["Find a player"]   = "查找玩家",
    ["Find a player by username or user ID and join their server."] = "用用户名或用户ID查找玩家并加入其服务器",
    ["Open or reopen a creator's personal recording server."] = "开启或重新开启创作者的私人录制服务器",
    ["Open or reopen a creator’s personal recording server."] = "开启或重新开启创作者的私人录制服务器",
    ["Open server"]     = "开启服务器",
    ["Notify guests and return them to a public server."] = "通知访客并把他们送回公共服务器",
    ["Close server"]    = "关闭服务器",
    ["Keyboard: W A S D · Q / E  ·  Mouse: hold right button to look  ·  Touch: on-screen controls  ·  Controller: sticks and triggers"] = "键盘: W A S D · Q / E  ·  鼠标: 按住右键转视角  ·  触屏: 屏幕控件  ·  手柄: 摇杆和扳机",
}

local PARTIAL = {
    -- 稀有度词（"5 - Legendary"、"8 - Secret" 都会翻到）
    ["Legendary"] = "传说",
    ["Mythic"]    = "神话",
    ["Divine"]    = "神圣",
    ["Cosmic"]    = "宇宙",
    ["Uncommon"]  = "罕见",
    ["Secret"]    = "神秘",
    ["Epic"]      = "史诗",
    ["Common"]    = "普通",
    ["Rare"]      = "稀有",

    -- 宠物/蛋名前缀（和上面本体名组合）
    ["Scrambled Mutation "] = "扰乱变异 ",
    ["Skeletal "]   = "骸骨 ",
    ["Shattered "]  = "破碎 ",
    ["Luminous "]   = "发光 ",
    ["Eternal "]    = "永恒 ",
    ["Golden "]     = "黄金 ",
    ["Silver "]     = "白银 ",
    ["Mecha "]      = "机甲 ",
    ["Experimental "] = "实验",
    ["Unstable DNA"] = "不稳定DNA",
    ["Biohazard"]   = "生化",
    ["Mutant "]     = "变异 ",
    ["Pure "]       = "纯 ",

    -- 蛋相关
    [" Eggs"] = " 蛋",
    [" Egg"]  = " 蛋",
    ["Egg ("] = "蛋 (",

    -- 动态状态文本里的固定片段
    ["No three matching pets"] = "没有三只匹配的宠物",
    ["Next Mech portal in"]    = "下个机甲传送门还有",
    -- "Auto Steal: 3" 这类 前缀+数字 状态
    ["Auto Steal:"]  = "自动偷蛋:",
    ["Auto Sell:"]   = "自动出售:",
    ["Auto Hatch:"]  = "自动孵化:",
    ["Auto Place:"]  = "自动放蛋:",
    ["Auto Fuse:"]   = "自动融合:",
    ["Auto Buy:"]    = "自动购买:",
    ["Lab egg matches"]        = "匹配的实验蛋",
    ["Favorite matches"]       = "匹配的收藏",
    ["Egg matches"]            = "匹配的蛋",
    ["Pet matches"]            = "匹配的宠物",
    ["favorited"]              = "已收藏",
    ["equipped"]               = "已装备",
    ["Eggs placed"]            = "已放蛋",
    ["pets for $"]             = "只宠物，价值 $",
    ["eggs for $"]             = "个蛋，价值 $",
    ["in bag"]                 = " 在背包",
    ["to mark"]                = " 待标记",
    ["Would you like to sell "] = "确定要出售 ",
    ["The vault is damaged and missing "] = "保险库损坏，缺少 ",
    [" parts"]                 = " 个零件",
    ["You have "]              = "你有 ",
    [" crystals"]              = " 水晶",
    ["You earn "]              = "你离线可赚 ",
    ["/Day offline!"]          = "/天!",
    [" selected"]              = " 项已选",
    ["+50% Grow Speed! Higher "] = "+50%生长速度! 更高 ",
    [" Fruit Chance!"]         = " 水果概率!",
    ["The Rift Overlord is spawning in: "] = "裂隙霸主即将出现: ",
    ["Infested Eggs spawn from the "] = "寄生蛋从 ",
    [" onwards. Look for the purple glow and steal it."] = " 区域起出现。找紫色光晕去偷。",
    ["Bring the infested Egg to "] = "把寄生蛋带给 ",
    [". Every feed fills his belly by "] = "。每喂一次涨 ",
    ["Fill him to "]           = "把它喂到 ",
    [" and he burps out a "]   = "，它会吐出 ",
    [" full of rare rewards!"] = "，全是稀有奖励!",
    ["Deposit "]               = "存入 ",
    ["The battle will begin in "] = "战斗开始倒计时: ",
    [" seconds"]               = " 秒",
    [" second"]                = " 秒",
    ["Carrying"]               = "搬运中",
    ["Returning"]              = "返回中",
    ["Stealing"]               = "偷蛋中",
    ["Hatching"]               = "孵化中",
    ["Fighting"]               = "战斗中",
    ["Selling"]                = "出售中",
    ["Hopping"]                = "换服中",
    ["Claiming"]               = "领取中",
    ["Waiting"]                = "等待中",
    ["Buying"]                 = "购买中",
    ["Fusing"]                 = "融合中",
    ["matches"]                = "匹配",
    ["pity"]                   = "保底",
    ["Stolen"]                 = "被偷",
    ["Found"]                  = "已找到",
    [" Active"]                = " 出战",
    ["Auto"]                   = "自动",

    -- ===== v3.2 新增子串 =====
    -- 宠物列表的稀有度后缀："Balrog [Eternal]" → "炎魔 [永恒]"
    [" [Eternal]"]   = " [永恒]",
    [" [Divine]"]    = " [神圣]",
    [" [Secret]"]    = " [神秘]",
    [" [Cosmic]"]    = " [宇宙]",
    [" [Mythic]"]    = " [神话]",
    [" [Legendary]"] = " [传说]",
    [" [Epic]"]      = " [史诗]",
    [" [Rare]"]      = " [稀有]",
    [" [Uncommon]"]  = " [罕见]",
    [" [Common]"]    = " [普通]",

    -- 刷新/掉落公告片段
    ["A Secret "]        = "一个神秘",
    ["A Eternal "]       = "一个永恒",
    [" Egg spawned in "] = " 蛋刷在了 ",
    ["You stole an "]    = "你偷到了",
    ["You fused "]       = "你融合了 ",
    [" started "]        = " 发起了 ",
    ["Dr. Scramble"]     = "乱蛋博士",
    ["Bring "]           = "放入",
    [" same Pets to Fuse"] = " 只相同宠物来融合",
    [" for $"]           = "，价值 $",
    [" pets"]            = " 只宠物",
    [" pets equipped"]   = " 只宠物已装备",
    [" to charge your egg!"] = " 给蛋充能!",
    ["Night, going again in "] = "夜晚，",
    ["Incubator"]        = "孵化器",

    -- 挂机统计面板（全大写标签 + 值片段）
    ["PING MS"]        = "延迟",
    ["ECONOMY"]        = "经济",
    ["INCOME"]         = "收益",
    ["TREADMILL"]      = "跑步机",
    ["STEALING"]       = "偷蛋中",
    ["EGGS STOLEN"]    = "已偷蛋数",
    ["BEST STEAL"]     = "最佳偷蛋",
    ["WORLD"]          = "世界",
    ["NIGHT TIMER"]    = "夜晚计时",
    ["SESSION TIME"]   = "本次时长",
    ["STATUS"]         = "状态",
    ["ACTIVITY"]       = "活动",
    ["DR SCRAMBLE"]    = "乱蛋博士",
    ["MECH PORTAL"]    = "机甲传送门",
    ["BOSS MASTERY"]   = "Boss精通",
    ["SAMPLES"]        = "样本",
    ["MECH FIGHTS"]    = "机甲战斗",
    ["COLLECTION"]     = "收集",
    ["TOP PETS"]       = "顶级宠物",
    ["TOP EGGS"]       = "顶级蛋",
    ["STEAL HISTORY"]  = "偷蛋记录",
    ["EGGS"]           = "蛋",
    ["PETS"]           = "宠物",
    ["   until open"]  = "   距开启",
    ["   join now"]    = "   已开启，快来",
    ["   players"]     = " 位玩家",
    ["   eggs reset"]  = "   蛋已重置",
    ["  rewards ready"] = " 个奖励可领",
    ["   last "]       = "   上次 ",
    [" ago"]           = " 前",
    ["   placed"]      = " 只已放置",
    ["   ready"]       = " 就绪",
    ["   growing"]     = " 生长中",
    [" speed/h"]       = " 速度/时",
    ["   next "]       = "   下一档 ",
    ["   boss in "]    = "   Boss还有 ",
    ["h ago"]          = "小时",
    ["m ago"]          = "分钟",
    ["s ago"]          = "秒",
    ["d ago"]          = "天",

    -- v3.2 第二批：蝴蝶绽放/统计值片段
    ["Next Butterfly Bloom in "] = "下次蝴蝶绽放还有 ",
    [" Scrambled in bag"] = " 个扰乱蛋在背包",
    ["   all rewards claimed"] = "   奖励已全部领取",
    ["   next reward at "] = "   下一档奖励 ",
    ["Off  |  "]       = "关  |  ",
    ["Amount ("]       = "数量（",
    ["Minutes ("]      = "分钟（",

    -- v3.2 第三批：状态机前缀（放子串表才能带动后面的动态部分）
    ["Smashing the core"] = "猛砸核心",
    ["Ball phase, waiting for it to lock on"] = "球阶段，等它锁定目标",
    ["Chasing Dr Scramble"] = "追击乱蛋博士",
    ["Fighting Mech"]  = "机甲战斗中",
    ["Fighting Ejecting"] = "弹射阶段",
    ["Night, deciding egg or boss after the field resets"] = "夜晚，场地重置后决定偷蛋还是打Boss",
    ["Phase Mech, waiting for the boss"] = "机甲阶段，等待Boss出现",
    ["Phase Waiting, waiting for the boss"] = "等待阶段，等Boss出现",
    ["Next fuse"]      = "下次融合",

    -- 大绽放/救龙任务句片段
    ["Every 30 minutes, "] = "每 30 分钟，",
    [" begins! Break "] = " 开始！砸 ",
    [" to collect Crystals."] = " 收集水晶。",
    ["Great Bloom Odds"] = "大绽放概率",
    ["Complete "]      = "完成 ",
    [" to forge "]     = "，铸造 ",
    [" and save the "] = "，救出 ",
    ["MISSIONS"]       = "任务",
    ["KEYS"]           = "钥匙",
    ["DRAGON!"]        = "巨龙!",
}

-- 动态文本模式（带捕获组，按顺序应用，先锚定后宽松）
local PATTERNS = {
    {"^(%d+) Eggs? Left$", "剩 %1 个蛋"},
    {"^(%d+) Pets? Left$", "剩 %1 只宠物"},
    {"^(%d[%d,]*) comments$", "%1 条评论"},
    {"^Pets: (%d+)/(%d+)$", "宠物: %1/%2"},
    {"^Unlocked: (%d+)/(%d+)$", "已解锁: %1/%2"},
    {"^in (%d+)h (%d+)m$", "%1小时%2分后"},
    {"^in (%d+)m (%d+)s$", "%1分%2秒后"},
    {"^in (%d+)m$", "%1分后"},
    {"^in (%d+)s$", "%1秒后"},
    {"^The battle will begin in (%d+) seconds?$", "战斗开始倒计时: %1 秒"},
    {"^ARRIVING IN (%d+)$", "即将到达 %1"},
    {"^ARRIVING IN$", "即将到达"},
    {"^(%d+) Eggs$", "%1 个蛋"},
    {"^(%d+) Egg$", "%1 个蛋"},
    {"^1 in ([%d%.]+)$", "概率 1/%1"},
    {"^(%d+)hr (%d+)m$", "%1小时%2分"},
    {"^(%d+)h (%d+)m (%d+)s$", "%1小时%2分%3秒"},
    {"^(%d+)h (%d+)m$", "%1小时%2分"},
    {"^(%d+)m (%d+)s$", "%1分%2秒"},
    {"^Charges (%d+)  Eggs (%d+)/(%d+)  Tries (%d+)  Applied (%d+)$", "充能 %1  蛋 %2/%3  尝试 %4  已用 %5"},
    {"^Remove (%d+)$", "移除 %1"},
    {"^Sell %((%d+)%)$", "出售（%1）"},
    {"^%(([%d,]+)Kg%)$", "（%1公斤）"},
    {"([%d,]+)Kg", "%1公斤"},
    {"^(%$[%d%.,%a]+)/s$", "%1/秒"},
    {"^Rotates in: ", "轮换剩余: "},
    {"^Stocks In: ", "补货倒计时: "},
    {"^LEAVES IN: ", "离开倒计时: "},
    {"^Ends in ", "结束倒计时: "},
    {"^Starts ", "开始于 "},
    {"^Chase ", "追捕 "},
    {"^Banner chance ", "横幅概率 "},
    {"^Unlocked: ", "已解锁: "},
    {"^User ID: ", "用户ID: "},
    {"^Total Videos: ", "视频总数: "},
    {"^TOTAL VIDEOS: ", "视频总数: "},
    {"^Current: ", "当前: "},
    {"^Save: ", "保存: "},
    {"^Startup Config: ", "启动配置: "},
    {"^Mech portal is open  |  boss spawns in ", "机甲传送门已开启  |  Boss 出现倒计时: "},
    {"^In the arena  |  boss spawns in ", "已进竞技场  |  Boss 出现倒计时: "},
    {"(%d+)h (%d+)m", "%1小时%2分"},
    {"(%d+)m (%d+)s", "%1分%2秒"},
    {"(%d+)h$", "%1小时"},
    {"(%d+)m$", "%1分"},
    {"(%d+)s$", "%1秒"},
    {"(%d+):(%d%d)$", "%1分%2秒"},
    {"^(%d+)D (%d+)HR$", "%1天%2小时"},

    -- v3.2：机甲Boss多阶段状态行
    {"  |  boss (%d+) / (%d+)", "  |  Boss %1/%2"},
    {"  |  hits (%d+) / (%d+)", "  |  击中 %1/%2"},
    {"  |  stage (%d+) / (%d+)", "  |  阶段 %1/%2"},
    {"  |  core (%d+)", "  |  核心 %1"},
    {"  |  OVERHEAT", "  |  过热!"},
    {"^Nobody showed up%? Cowards! My mech waits for you in (.+)%.%.%.$", "没人来？胆小鬼！我的机甲在%1等你…"},
    {"^My MECH is complete! Find my portal in (.+) if you dare!$", "我的机甲完成了！敢来就来%1找我的传送门！"},
    {"^Bought (%d+)x ", "已购买 %1 个 "},

    -- v3.2：宠物卡片（收入/重量）、装备位、其他数字格式
    {"%((%$[%d%.,]+[KMBTQakmbtq]?)/s%)", "（%1/秒）"},
    {"^%+1 EQUIP %[(.+)%]$", "+1 装备位 [%1]"},
    {"^(%d+) Boss Kills$", "%1 次Boss击杀"},
    {"^ONLY%s-(%d+)$", "仅剩 %1"},
    {"^REROLL%s-(%d+)$", "重摇 %1 次"},
    {"^%+(%d+) min$", "+%1 分"},
    {"^Players (%d+)/(%d+)$", "玩家 %1/%2"},
    {"^ALL  (%d+)$", "全部 %1"},
    {"^(%d+) more$", "还需 %1 个"},
    {"^Loading part (%d+) / (%d+)$", "加载中 %1/%2"},
    {"^Eggs Grow ", "蛋生长"},
    {" faster!$", " 更快!"},
    {"%/h$", "/时"},
    {" chance ", " 概率 "},
    {"^You ", "你 "},
    {"^(%S+) liked this video$", "%1 赞了这条视频"},
    {"^(%S+) sent me flying! This isn't over%.%.%.$", "%1 把我打飞了！这没完…"},

    -- v3.2：魔幻森林活动任务
    {"^Stage (%d+)$", "第%1阶段"},
    {"^Finish Quest (%d+) & unlock Stage (%d+)$", "完成任务%1，解锁阶段%2"},
    {"^Steal (%d+) Enchanted Forest eggs$", "偷 %1 个魔幻森林蛋"},
    {"%+(%d+) Essence$", "+%1 精华"},
    {"^(%d+) / (%d+) Essence$", "精华 %1/%2"},
    {"^(%d+) studs$", "%1 格"},

    -- v3.2：Chilli 配置自动保存/加载
    {"^Auto save: ", "自动保存: "},
    {"^Auto load: ", "自动加载: "},
    {"^LAB   ", "实验室   "},
    {"^(%d+) FPS$", "%1 FPS"},
}

-- "Farm Tab  >  Dr Scramble Lab & Mech" 这类按键提示的页名
local TAB_HEADS = {
    ["Farm Tab"]      = "挂机页",
    ["Player Tab"]    = "玩家页",
    ["Predictor Tab"] = "预测页",
    ["Server Tab"]    = "服务器页",
    ["Misc Tab"]      = "杂项页",
    ["Settings Tab"]  = "设置页",
    ["Config Tab"]    = "配置页",
    ["Discord Tab"]   = "Discord页",
    ["Progress Tab"]  = "进度页",
}

return {
    EXACT     = EXACT,
    PARTIAL   = PARTIAL,
    PATTERNS  = PATTERNS,
    TAB_HEADS = TAB_HEADS,
}
